# Generated by Django 6.1 on 2026-09-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('amount', models.CharField(max_length=100)),
                ('education_level', models.CharField(choices=[('12th', '12th Pass'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('diploma', 'Diploma')], max_length=20)),
                ('eligibility', models.TextField()),
                ('income_limit', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('course', models.CharField(blank=True, max_length=100)),
                ('required_documents', models.TextField()),
                ('application_deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-application_deadline'],
            },
        ),
    ]
