# Generated by Django 6.1 on 2026-09-01 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_type', models.CharField(choices=[('job', 'Job'), ('scholarship', 'Scholarship'), ('scheme', 'Government Scheme'), ('skill', 'Skill Program'), ('business', 'Business Opportunity')], max_length=20)),
                ('opportunity_id', models.IntegerField()),
                ('opportunity_name', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='applied', max_length=20)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-applied_date'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar', models.BooleanField(default=False)),
                ('marksheet', models.BooleanField(default=False)),
                ('income_certificate', models.BooleanField(default=False)),
                ('community_certificate', models.BooleanField(default=False)),
                ('bank_details', models.BooleanField(default=False)),
                ('residence_certificate', models.BooleanField(default=False)),
                ('passport', models.BooleanField(default=False)),
                ('pan_card', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_checklist', to='accounts.userprofile')),
            ],
        ),
    ]
