# Generated by Django 4.2.7 on 2026-09-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_applicant_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='source_portal',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='application',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
