# Generated by Django 6.1 on 2026-09-01 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('education', models.CharField(blank=True, choices=[('10th', '10th Pass'), ('12th', '12th Pass'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('diploma', 'Diploma'), ('other', 'Other')], max_length=20)),
                ('course', models.CharField(blank=True, max_length=100)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated list of skills')),
                ('experience', models.TextField(blank=True, help_text='Work experience details')),
                ('annual_income', models.CharField(blank=True, max_length=50)),
                ('interests', models.CharField(blank=True, help_text='Comma-separated interests', max_length=100)),
                ('preferred_opportunity', models.CharField(blank=True, choices=[('jobs', 'Jobs & Employment'), ('scholarships', 'Scholarships'), ('schemes', 'Government Schemes'), ('skills', 'Skill Development'), ('business', 'Business Opportunities')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
