# Generated by Django 6.1 on 2026-09-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('investment_level', models.CharField(choices=[('low', 'Low (< ₹1,00,000)'), ('medium', 'Medium (₹1,00,000 - ₹5,00,000)'), ('high', 'High (> ₹5,00,000)')], max_length=20)),
                ('opportunity_level', models.CharField(choices=[('easy', 'Easy to Start'), ('moderate', 'Moderate'), ('challenging', 'Challenging')], max_length=20)),
                ('required_skills', models.TextField()),
                ('expected_income', models.CharField(max_length=200)),
                ('market_demand', models.CharField(max_length=100)),
                ('resources', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
