# Generated by Django 6.1 on 2026-09-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillprogram',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skillprogram',
            name='source_portal',
            field=models.CharField(blank=True, default='Skill India Digital', max_length=100),
        ),
        migrations.AddField(
            model_name='skillprogram',
            name='source_url',
            field=models.URLField(blank=True, default='https://www.skillindiadigital.gov.in/'),
        ),
    ]
