# Generated by Django 6.1 on 2026-09-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('agriculture', 'Agriculture'), ('education', 'Education'), ('employment', 'Employment'), ('housing', 'Housing'), ('financial', 'Financial Assistance'), ('healthcare', 'Healthcare'), ('skills', 'Skill Development'), ('women', 'Women & Children'), ('entrepreneurship', 'Entrepreneurship'), ('rural', 'Rural Development')], max_length=50)),
                ('description', models.TextField()),
                ('target_beneficiaries', models.TextField()),
                ('benefits', models.TextField()),
                ('eligibility', models.TextField()),
                ('required_documents', models.TextField()),
                ('application_process', models.TextField()),
                ('official_website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
