# Generated by Django 6.1 on 2026-09-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government_schemes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentscheme',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='source_portal',
            field=models.CharField(blank=True, default='myScheme.gov.in', max_length=100),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='source_url',
            field=models.URLField(blank=True, default='https://www.myscheme.gov.in/'),
        ),
    ]
